### ISSUE TITLE
Parese error on set_flags load_attached

### ISSUE THREAD

**Issue by schirner** [schirner/insteon-mqtt#1]
```
insteon-mqtt config.yaml set-flags entrance load_attached=0
```

causes:

```
2022-12-13 11:03:32.109 UI Mqtt: Commanding keypad_linc device 44.cb.b7 (entrance) cmd=set_flags
2022-12-13 11:03:32.109 INFO Base: Device 44.cb.b7 (entrance) cmd: set flags
2022-12-13 11:03:32.110 ERROR Mqtt: Error running command set_flags on device 44.cb.b7 (entrance)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/insteon_mqtt/mqtt/Mqtt.py", line 332, in handle_cmd
    cmd_func(on_done=on_done, **data)
  File "/usr/lib/python3.9/site-packages/insteon_mqtt/device/base/Base.py", line 499, in set_flags
    seq.run()
  File "/usr/lib/python3.9/site-packages/insteon_mqtt/CommandSeq.py", line 102, in run
    self.on_done(True, None, None)
  File "/usr/lib/python3.9/site-packages/insteon_mqtt/CommandSeq.py", line 135, in on_done
    entry.run(self.device, self.on_done)
  File "/usr/lib/python3.9/site-packages/insteon_mqtt/CommandSeq.py", line 203, in run
    self.func(*self.args, on_done=on_done, **self.kwargs)
TypeError: set_load_attached() got an unexpected keyword argument 'load_attached'
```

Version 1.1.1

**Comment by schirner** [comment]
KeypadLinc.set_load_attached did not follow the API changes on set_flags calls (e.g. as set_led_follow_mask). In result, arguments passed in don't match what the function provides, throwing the exception above. 

Test cases did not catch it since they don't go through the set_flags indirection.

**Comment by schirner** [comment]
`test_set_flags` might have gotten it, but i am unsure
